name: Build Packer Custom Image

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build and Test Web Application & Create Custom AMI
    # if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    env:
      PROD_DB_HOST: ${{ secrets.PROD_DB_HOST }}
      PROD_DB_USER: ${{ secrets.PROD_DB_USER }}
      PROD_DB_PASSWORD: ${{ secrets.PROD_DB_PASSWORD }}
      PROD_DB_NAME: ${{ secrets.PROD_DB_NAME }}
      PROD_DB_PORT: ${{ secrets.PROD_DB_PORT }}

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Node.js environment
      - name: Set up Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: "16"

      # Step 3: Install PostgreSQL
      - name: Install PostgreSQL
        run: |
          sudo apt-get update
          sudo apt-get install -y postgresql postgresql-contrib
          sudo systemctl start postgresql

      # Step 4: Set up PostgreSQL user and database with logs
      - name: Set up PostgreSQL user and database
        run: |
          sudo service postgresql start
          if [[ -z "${{ secrets.PROD_DB_USER }}" || -z "${{ secrets.PROD_DB_PASSWORD }}" ]]; then
          echo "DB_USER or DB_PASSWORD secret is not set."
          exit 1
          fi
          if sudo -u postgres psql -tc "SELECT 1 FROM pg_roles WHERE rolname='${{ secrets.PROD_DB_USER }}';" | grep -q 1; then
          echo "User exists, altering password..."
          sudo -u postgres psql -c "ALTER USER ${{ secrets.PROD_DB_USER }} WITH PASSWORD '${{ secrets.PROD_DB_PASSWORD }}';"
          else
          echo "User does not exist, creating user..."
          sudo -u postgres psql -c "CREATE USER ${{ secrets.PROD_DB_USER }} WITH PASSWORD '${{ secrets.PROD_DB_PASSWORD }}';"
          fi
          sudo -u postgres psql -tc "SELECT 1 FROM pg_database WHERE datname='${{ secrets.PROD_DB_NAME }}';" | grep -q 1 || sudo -u postgres psql -c "CREATE DATABASE ${{ secrets.PROD_DB_NAME }} OWNER ${{ secrets.PROD_DB_USER }};"

      # Step 5: Run integration tests
      - name: Install dependencies and run tests
        run: |
          npm install
          npm run
        env:
          PROD_DB_HOST: ${{ secrets.PROD_DB_HOST }}
          PROD_DB_USER: ${{ secrets.PROD_DB_USER }}
          PROD_DB_PASSWORD: ${{ secrets.PROD_DB_PASSWORD }}
          PROD_DB_NAME: ${{ secrets.PROD_DB_NAME }}
          PROD_DB_PORT: ${{ secrets.PROD_DB_PORT }}

      # Step 6: Zip the entire repository
      - name: Zip application code
        run: |
          zip -r webapp.zip .

      # Step 6: Set up the environment file
      - name: Setup Environment File
        run: |
          mkdir -p ./environment
          cat << EOF > ./environment/development.env
          PROD_DB_USER=${{ secrets.PROD_DB_USER }}
          PROD_DB_HOST=${{ secrets.PROD_DB_HOST }}
          PROD_DB_NAME=${{ secrets.PROD_DB_NAME }}
          PROD_DB_PASSWORD=${{ secrets.PROD_DB_PASSWORD }}
          PROD_DB_PORT=${{ secrets.PROD_DB_PORT }}
          DB_DIALECT=${{ secrets.DB_DIALECT }}
          PORT=${{ secrets.PORT }}
          AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION=${{ secrets.AWS_REGION }}
          S3_BUCKET=${{ secrets.S3_BUCKET }}
          EOF
        shell: bash

      - name: Check if environment file exists
        run: ls -l ./environment/development.env

      - name: Show environment file content
        run: cat ./environment/development.env

      # Step 7: Upload artifact (optional)
      - name: Upload webapp artifact
        uses: actions/upload-artifact@v3
        with:
          name: webapp.zip
          path: webapp.zip

      # Step 8: Install Packer
      - name: Install Packer
        run: |
          sudo apt-get update && sudo apt-get install -y wget unzip
          wget https://releases.hashicorp.com/packer/1.8.4/packer_1.8.4_linux_amd64.zip
          unzip -o packer_1.8.4_linux_amd64.zip -d /usr/local/bin/

      # Step 9: AWS configure
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      # Step 10: Initialize Packer
      - name: Initialize Packer (Install Plugins)
        run: |
          packer init packer/ubuntu-24.04.pkr.hcl

      # Step 10: Run Packer Build
      - name: Run Packer Build
        run: |
          packer build \
          -var "prod_db_user=${{ secrets.PROD_DB_USER }}" \
          -var "prod_db_password=${{ secrets.PROD_DB_PASSWORD }}" \
          -var "prod_db_name=${{ secrets.PROD_DB_NAME }}" \
          -var "prod_db_port=${{ secrets.PROD_DB_PORT }}" \
          -var "aws_profile=${{ secrets.AWS_PROFILE }}" \
          -var "aws_region=${{ secrets.AWS_REGION }}" \
          -var "aws_instance_type=${{ secrets.AWS_INSTANCE_TYPE }}" \
          -var "aws_source_ami=${{ secrets.AWS_SOURCE_AMI }}" \
          -var "aws_vpc_id=${{ secrets.AWS_VPC_ID }}" \
          -var "aws_subnet_id=${{ secrets.AWS_SUBNET_ID }}" \
          -var "volume_size=${{ secrets.VOLUME_SIZE }}" \
          -var "aws_demo_user=${{ secrets.DEMO_USER }}" \
          -var "aws_dev_user=${{ secrets.DEV_USER }}" \
          packer/ubuntu-24.04.pkr.hcl

      # Step 4: Extract and Save AMI ID
      - name: Get Latest AMI ID
        id: ami_id
        run: |
          echo "AMI_ID=$(cat latest_ami_id.txt)" >> $GITHUB_ENV
          echo "::set-output name=ami_id::$(cat latest_ami_id.txt)"

      # Step 5: Trigger Terraform Workflow in Another Repo
      - name: Trigger Terraform Workflow
        if: success()
        uses: peter-evans/repository-dispatch@v2
        with:
          repository: csye6225-cloud-computing-sarala/tf-aws-infra
          event-type: update-launch-template
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
          client-payload: |
            {
              "ami_id": "${{ env.ami_id }}"
            }
