name: Packer Template Check

on:
  pull_request:
    branches:
      - main

jobs:
  packer-check:
    name: Packer Format and Validate
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Install dependencies if required (e.g., for Node.js build)
      - name: Set up Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: "14"

      # Step 3: Build the application (if necessary)
      - name: Run Integration tests and create webapp.zip
        run: |
          npm install
          zip -r webapp.zip .   # Adjust the directory to match your requirements

      # Step 4: Manually install Packer
      - name: Install Packer
        run: |
          sudo apt-get update && sudo apt-get install -y wget unzip
          wget https://releases.hashicorp.com/packer/1.8.4/packer_1.8.4_linux_amd64.zip
          unzip -o packer_1.8.4_linux_amd64.zip -d /usr/local/bin/

      # Step 5: Set up the environment file
      - name: Setup Environment File
        run: |
          mkdir -p ./environment
          cat << EOF > ./environment/development.env
          PROD_DB_USER=${{ secrets.PROD_DB_USER }}
          PROD_DB_HOST=${{ secrets.PROD_DB_HOST }}
          PROD_DB_NAME=${{ secrets.PROD_DB_NAME }}
          PROD_DB_PASSWORD=${{ secrets.PROD_DB_PASSWORD }}
          PROD_DB_PORT=${{ secrets.PROD_DB_PORT }}
          DB_DIALECT=${{ secrets.DB_DIALECT }}
          PORT=${{ secrets.PORT }}
          EOF
        shell: bash

      - name: Check if environment file exists
        run: ls -l ./environment/development.env

      - name: Show environment file content
        run: cat ./environment/development.env

      # Step 5: Run packer init to install required plugins
      - name: Initialize Packer
        run: |
          packer init ./packer/ubuntu-24.04.pkr.hcl

      # Step 6: Run packer fmt --check to ensure no formatting issues
      - name: Check Packer formatting
        run: |
          packer fmt -check -diff ./packer
        # If the packer fmt command makes changes, the workflow will fail.

      # Step 7: Run packer validate to validate the template using GitHub secrets
      - name: Validate Packer template
        run: |
          packer validate -var "prod_db_user=${{ secrets.PROD_DB_USER }}" \
                     -var "prod_db_password=${{ secrets.PROD_DB_PASSWORD }}" \
                     -var "prod_db_name=${{ secrets.PROD_DB_NAME }}" \
                     -var "prod_db_port=${{ secrets.PROD_DB_PORT }}" \
                     -var "aws_profile=${{ secrets.AWS_PROFILE }}" \
                     -var "aws_region=${{ secrets.AWS_REGION }}" \
                     -var "aws_instance_type=${{ secrets.AWS_INSTANCE_TYPE }}" \
                     -var "aws_source_ami=${{ secrets.AWS_SOURCE_AMI }}" \
                     -var "aws_vpc_id=${{ secrets.AWS_VPC_ID }}" \
                     -var "aws_subnet_id=${{ secrets.AWS_SUBNET_ID }}" \
                     -var "volume_size=${{ secrets.VOLUME_SIZE }}" \
                     -var "demo_account_id=${{ secrets.DEMO_ACCOUNT_ID }}" \./packer/ubuntu-24.04.pkr.hcl
